### PR TITLE
Add reference to dom2hscript in Readme

### PR DESCRIPTION
**Pull request by AkeemMcLennon**
Hello everyone,

I ended up creating a client side version of twilson63/html2hscript that uses the browser's built in DOM and CSS parser at https://github.com/AkeemMcLennon/dom2hscript

Although I'm still using html2hscript in the backend, the 200kb dependency on htmlparser2 was too large for use in production. However, this dependency is no longer necessary in the browser context.

### CODE REVIEW

**Comment by dominictarr** [comment]
sounds good! just out of curiosity can you describe how you are using dom2hscript? It's always interesting to hear how someone is using you module and a very useful guide when making future decisions regards pull requests etc

**Comment by AkeemMcLennon** [comment]
@dominictarr I'm not sure if I can get into specifics, but I'm basically using it in conjunction with virtual-dom to render changes to customer generated html in realtime.

**Comment by dominictarr** [comment]
@AkeemMcLennon if you are generating a string and then running that in other browsers, I'm a little worried it may be a XSS or Injection Atttack vector. Are you doing anything to validate/escape the output?

(I'm guessing that you parse it in one browser, then send it to others, via a server? or is it just a way to get people to enter html, and integrate that back as vdom code in their own browser?)

**Comment by AkeemMcLennon** [comment]
@dominictarr Thanks for the feedback! The browser that generates the hyperscript is the same browser that's running the code. The raw HTML is also sanitized for scripts.

**Pull request merged**
