### PR TITLE
added hyperscript tools to readme

### PR DESCRIPTION
**Pull request by twilson63**
PR referring to #27

### CODE REVIEW

**Comment by Raynos** [comment]
lgtm.

**Comment by unframework** [comment]
Nicely done! It might be helpful to include a link to my original command-line mode utility as well: https://github.com/Matt-Esch/virtual-dom/pull/206

**Comment by dominictarr** [comment]
@unframework can you make a pull request?

**Comment by dominictarr** [comment]
merged into 1.4.5

**Pull request merged**
